version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    #env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=liftdb
    ports:
      - 3309:3306
    volumes:
      - db:/var/lib/mysql
#  app:
#    depends_on:
#      - mysqldb
#    build: ./lift
#    restart: on-failure
#    env_file: ./.env
#    ports:
#      - 8777:8080
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
#        "spring.datasource.username" : "$MYSQLDB_USER",
#        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
#        "spring.jpa.hibernate.ddl-auto" : "create"
#      }'
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true

volumes:
  db: